name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install addlicense
        run: |
          go install github.com/google/addlicense@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build core package
        run: pnpm core build:prod

      - name: Build cli package
        run: pnpm cli build:prod

      - name: Install texlive-latex
        run: |
          sudo apt update
          sudo apt install -y texlive-xetex texlive-fonts-extra texlive-lang-all
          xetex -v

      - name: Run check
        run: pnpm check:ci

      - name: Run tests
        run: pnpm test:cov

      - name: Install Noto CJK fonts
        run: |
          sudo apt install fonts-noto-cjk fonts-noto-cjk-extra

      - name: Build resume
        run: |
          node packages/cli/dist/cli.js -V
          node packages/cli/dist/cli.js new
          node packages/cli/dist/cli.js build --verbose resume.yml

      - name: Check files
        if: always()
        run: |
          ls -lah

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: yamlresume-sample
          path: |
            resume.yml
            resume.tex
            resume.pdf
