name: publish-base

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the image (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yamlresume/yamlresume-base
          tags: |
            type=raw,value=${{ github.event.inputs.tag || github.ref_name }}

      - name: Build and push docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.base
          platforms: ${{ github.event.inputs.platforms || 'linux/amd64,linux/arm64' }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
